apiVersion: apps/v1
kind: Deployment
metadata:
    name: scrap-service
    labels:
        app: scrap-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: scrap-service
    template:
        metadata:
            labels:
                app.kubernetes.io/name: scrap-service
        spec:
            containers:
                - image: 346287969518.dkr.ecr.eu-central-1.amazonaws.com/scrap-service:develop
                  imagePullPolicy: Always
                  name: scrap-service
                  resources:
                      requests:
                          memory: "50M"
                          cpu: "125m"
                      limits:
                          memory: "1500M"
                          cpu: "1"
                  volumeMounts:
                      - name: scrapData
                        mountPath: /usr/app/
                        subPath: csv
            volumes:
                - name: scrapData
                  # This AWS EBS volume must already exist.
                  awsElasticBlockStore:
                      volumeID: "<volume id>"
                      fsType: ext4
